export const medicinesData = [
    {
        id: 1,
        name: 'Dolo-650',
        manufacturer: 'Micro Labs',
        totalSales: 50000,
        adverseEvents: 124,
        riskDistribution: [
            { level: 'Level 1', value: 90, color: '#10b981' },
            { level: 'Level 2', value: 6, color: '#3b82f6' },
            { level: 'Level 3', value: 2, color: '#f59e0b' },
            { level: 'Level 4', value: 1.5, color: '#ef4444' },
            { level: 'Level 5', value: 0.5, color: '#7f1d1d' },
        ],
        batchData: [
            { batch: 'Batch A', sales: 15000, events: 20 },
            { batch: 'Batch B', sales: 18000, events: 45 },
            { batch: 'Batch C', sales: 17000, events: 59 },
        ],
        symptoms: ['Nausea', 'Dizziness', 'Headache', 'Fatigue', 'Rash', 'Vomiting'],
        sentiment: 'Moderate Concern',
        summary: 'Batch C shows elevated adverse event rate compared to sales volume. Recommend batch investigation.',
        aiAction: 'Initiate quality control review for Batch C. Monitor for additional reports in next 48 hours.',
    },
    {
        id: 2,
        name: 'Augmentin-625',
        manufacturer: 'GSK',
        totalSales: 35000,
        adverseEvents: 89,
        riskDistribution: [
            { level: 'Level 1', value: 85, color: '#10b981' },
            { level: 'Level 2', value: 10, color: '#3b82f6' },
            { level: 'Level 3', value: 3, color: '#f59e0b' },
            { level: 'Level 4', value: 1.5, color: '#ef4444' },
            { level: 'Level 5', value: 0.5, color: '#7f1d1d' },
        ],
        batchData: [
            { batch: 'Batch X', sales: 12000, events: 30 },
            { batch: 'Batch Y', sales: 11000, events: 28 },
            { batch: 'Batch Z', sales: 12000, events: 31 },
        ],
        symptoms: ['Diarrhea', 'Stomach Pain', 'Nausea', 'Allergic Reaction'],
        sentiment: 'Low Risk',
        summary: 'Adverse event rate consistent across batches. Within expected range for antibiotic class.',
        aiAction: 'Continue routine monitoring. No immediate action required.',
    },
    {
        id: 3,
        name: 'Remsima (Infliximab)',
        manufacturer: 'Celltrion',
        totalSales: 2500,
        adverseEvents: 67,
        riskDistribution: [
            { level: 'Level 1', value: 70, color: '#10b981' },
            { level: 'Level 2', value: 15, color: '#3b82f6' },
            { level: 'Level 3', value: 8, color: '#f59e0b' },
            { level: 'Level 4', value: 5, color: '#ef4444' },
            { level: 'Level 5', value: 2, color: '#7f1d1d' },
        ],
        batchData: [
            { batch: 'Batch 1', sales: 800, events: 18 },
            { batch: 'Batch 2', sales: 850, events: 25 },
            { batch: 'Batch 3', sales: 850, events: 24 },
        ],
        symptoms: ['Infusion Reaction', 'Fever', 'Chills', 'Breathing Difficulty', 'Chest Pain'],
        sentiment: 'High Alert',
        summary: 'Elevated adverse event rate for biologic drug. Higher than expected Level 4-5 events.',
        aiAction: 'URGENT: Review prescribing guidelines. Consider additional patient monitoring protocols.',
    },
    {
        id: 4,
        name: 'Paracetamol 500mg',
        manufacturer: 'Various',
        totalSales: 120000,
        adverseEvents: 45,
        riskDistribution: [
            { level: 'Level 1', value: 95, color: '#10b981' },
            { level: 'Level 2', value: 3, color: '#3b82f6' },
            { level: 'Level 3', value: 1.5, color: '#f59e0b' },
            { level: 'Level 4', value: 0.5, color: '#ef4444' },
            { level: 'Level 5', value: 0, color: '#7f1d1d' },
        ],
        batchData: [
            { batch: 'Batch P1', sales: 40000, events: 15 },
            { batch: 'Batch P2', sales: 40000, events: 15 },
            { batch: 'Batch P3', sales: 40000, events: 15 },
        ],
        symptoms: ['Mild Nausea', 'Drowsiness'],
        sentiment: 'Low Risk',
        summary: 'Excellent safety profile. Adverse events well within acceptable range.',
        aiAction: 'No action required. Continue standard monitoring.',
    },
];
